name: Gitleaks Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important: fetch the full history for a comprehensive scan

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v3
        with:
          args: --no-git-history --config-path .gitleak.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
