name: PR Security & Quality Scan

on:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          pip install --upgrade pip
          pip install semgrep==1.82.0

      - name: Run Semgrep SAST Scan
        run: |
          semgrep ci --config "p/ci" --publish-token ${{ secrets.SEMGREP_APP_TOKEN }} --json --output semgrep-results.json

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.json
