name: PR Scan

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  pr_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "https://github.com/returntocorp/semgrep-rules"   # your ruleset
          path: "."        # scan only changed files
