name: Trivy FS + Secret Scan on PR

on:
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Create Trivy Secret Config
        run: |
          mkdir -p ./secret-config
          cat > ./secret-config/trivy.yaml <<'EOF'
          rules:
            - id: generic-secret
              category: general
              title: Generic Secret Detection
              severity: CRITICAL
              regex: (?i)(?P<key>(token|apikey|secret|passwd|password|auth|key))(=|:).{0,5}['"]?(?P<secret>[0-9a-zA-Z\-_=]{8,64})['"]?
              path: .*\.((py|json|js|ts|yaml|yml|env|Dockerfile))$
          enable-builtin-rules:
            - aws-access-key-id
            - aws-secret-access-key
            - github-pat
            - private-key
            - generic-api-key
            - basic-auth
            - jwt
          EOF

      - name: Run Trivy FS Scan
        run: |
          trivy fs --format table -o trivy-fs-report.txt .

      - name: Run Trivy Secret Scan
        run: |
          trivy fs --security-checks secret --secret-config ./secret-config/trivy.yaml --format table -o trivy-secret-report.txt .

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-fs-report.txt
            trivy-secret-report.txt
