name: Trivy FS Scan on PR

on:
  pull_request:
    branches:
      - main

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy FS Scan
        run: trivy fs --format json -o trivy-report.json .

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
