name: Secret Scan

on:
  push:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Run Secret Scan
        run: |
          trivy fs --scanners secret \
            --secret-config ./trivy-secret.yaml \
            --format table -o trivy-secret-report.txt .

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-secret-report
          path: trivy-secret-report.txt
