name: Trivy FS Scan on PR

on:
  pull_request:
    branches:
      - main

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Run Trivy FS Scan (JSON + TXT)
        run: |
          trivy fs --format json -o trivy-report.json .
          trivy fs --format table -o trivy-report.txt .

     - name: Upload Trivy Reports
       uses: actions/upload-artifact@v4
       with:
       name: trivy-reports
       path: |
         trivy-report.json
         trivy-report.txt
